run tests:
  stage: test
  tags:
    - rixtest
  script:
    - echo "Starting Test"
    - python3 -m venv halpyvenv
    - source halpyvenv/bin/activate
    - pip install pytest pytest-cov pytest-asyncio
    - pip install -r requirements.txt
    - coverage run -m pytest
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml